#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : tiff
Version  : 360
Release  : 53
URL      : file:///insilications/build/clearlinux/packages/tiff/tiff-360.tar.gz
Source0  : file:///insilications/build/clearlinux/packages/tiff/tiff-360.tar.gz
Summary  : Tag Image File Format (TIFF) library.
Group    : Development/Tools
License  : MIT libtiff
Requires: tiff-bin = %{version}-%{release}
Requires: tiff-lib = %{version}-%{release}
Requires: tiff-man = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-scons
BuildRequires : findutils
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : libjpeg-turbo-dev
BuildRequires : libjpeg-turbo-staticdev
BuildRequires : libwebp-dev
BuildRequires : libwebp-staticdev
BuildRequires : mesa-dev
BuildRequires : pkgconfig(ice)
BuildRequires : pkgconfig(zlib)
BuildRequires : xz-dev
BuildRequires : xz-staticdev
BuildRequires : zlib-dev
BuildRequires : zlib-staticdev
BuildRequires : zstd-dev
BuildRequires : zstd-staticdev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
This directory contains various contributions from libtiff users.

%package bin
Summary: bin components for the tiff package.
Group: Binaries

%description bin
bin components for the tiff package.


%package dev
Summary: dev components for the tiff package.
Group: Development
Requires: tiff-lib = %{version}-%{release}
Requires: tiff-bin = %{version}-%{release}
Provides: tiff-devel = %{version}-%{release}
Requires: tiff = %{version}-%{release}

%description dev
dev components for the tiff package.


%package dev32
Summary: dev32 components for the tiff package.
Group: Default
Requires: tiff-lib32 = %{version}-%{release}
Requires: tiff-bin = %{version}-%{release}
Requires: tiff-dev = %{version}-%{release}

%description dev32
dev32 components for the tiff package.


%package doc
Summary: doc components for the tiff package.
Group: Documentation
Requires: tiff-man = %{version}-%{release}

%description doc
doc components for the tiff package.


%package lib
Summary: lib components for the tiff package.
Group: Libraries

%description lib
lib components for the tiff package.


%package lib32
Summary: lib32 components for the tiff package.
Group: Default

%description lib32
lib32 components for the tiff package.


%package man
Summary: man components for the tiff package.
Group: Default

%description man
man components for the tiff package.


%package staticdev
Summary: staticdev components for the tiff package.
Group: Default
Requires: tiff-dev = %{version}-%{release}

%description staticdev
staticdev components for the tiff package.


%package staticdev32
Summary: staticdev32 components for the tiff package.
Group: Default
Requires: tiff-dev32 = %{version}-%{release}

%description staticdev32
staticdev32 components for the tiff package.


%prep
%setup -q -n tiff
cd %{_builddir}/tiff
pushd ..
cp -a tiff build32
popd

%build
unset http_proxy
unset https_proxy
unset no_proxy
export SSL_CERT_FILE=/var/cache/ca-certs/anchors/ca-certificates.crt
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1611836173
export GCC_IGNORE_WERROR=1
## altflags_pgo content
## pgo generate
export PGO_GEN="-fprofile-generate=/var/tmp/pgo -fprofile-dir=/var/tmp/pgo -fprofile-abs-path -fprofile-update=atomic -fprofile-arcs -ftest-coverage --coverage -fprofile-partial-training"
export CFLAGS_GENERATE="-O3 -march=native -mtune=native -falign-functions=32 -fno-semantic-interposition -fno-stack-protector -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -mtls-dialect=gnu2 -fno-math-errno -fno-trapping-math -pipe -fPIC -ffat-lto-objects $PGO_GEN"
export FCFLAGS_GENERATE="-O3 -march=native -mtune=native -falign-functions=32 -fno-semantic-interposition -fno-stack-protector -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -mtls-dialect=gnu2 -fno-math-errno -fno-trapping-math -pipe -fPIC -ffat-lto-objects $PGO_GEN"
export FFLAGS_GENERATE="-O3 -march=native -mtune=native -falign-functions=32 -fno-semantic-interposition -fno-stack-protector -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -mtls-dialect=gnu2 -fno-math-errno -fno-trapping-math -pipe -fPIC -ffat-lto-objects $PGO_GEN"
export CXXFLAGS_GENERATE="-O3 -march=native -mtune=native -falign-functions=32 -fno-semantic-interposition -fno-stack-protector -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -mtls-dialect=gnu2 -fno-math-errno -fno-trapping-math -fvisibility-inlines-hidden -pipe -fPIC -ffat-lto-objects $PGO_GEN"
export LDFLAGS_GENERATE="-O3 -march=native -mtune=native -falign-functions=32 -fno-semantic-interposition -fno-stack-protector -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -mtls-dialect=gnu2 -fno-math-errno -fno-trapping-math -pipe -fPIC -ffat-lto-objects $PGO_GEN"
## pgo use
## -ffat-lto-objects -fno-PIE -fno-PIE -m64 -no-pie -fpic -fvisibility=hidden
## gcc: -feliminate-unused-debug-types -fipa-pta -flto=16 -Wno-error -Wp,-D_REENTRANT -fno-common
export PGO_USE="-fprofile-use=/var/tmp/pgo -fprofile-dir=/var/tmp/pgo -fprofile-abs-path -fprofile-correction -fprofile-partial-training"
export CFLAGS_USE="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -fPIC -ffat-lto-objects $PGO_USE"
export FCFLAGS_USE="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -fPIC -ffat-lto-objects $PGO_USE"
export FFLAGS_USE="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -fPIC -ffat-lto-objects $PGO_USE"
export CXXFLAGS_USE="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -fvisibility-inlines-hidden -pipe -fPIC -ffat-lto-objects $PGO_USE"
export LDFLAGS_USE="-g -O3 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -funroll-loops -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -fPIC -ffat-lto-objects $PGO_USE"
export AR=/usr/bin/gcc-ar
export RANLIB=/usr/bin/gcc-ranlib
export NM=/usr/bin/gcc-nm
#export CCACHE_DISABLE=1
## altflags_pgo end
export CFLAGS="${CFLAGS_GENERATE}"
export CXXFLAGS="${CXXFLAGS_GENERATE}"
export FFLAGS="${FFLAGS_GENERATE}"
export FCFLAGS="${FCFLAGS_GENERATE}"
export LDFLAGS="${LDFLAGS_GENERATE}"
%reconfigure --enable-shared --enable-static
make  %{?_smp_mflags}

make VERBOSE=1 V=1 %{?_smp_mflags} check
make clean
export CFLAGS="${CFLAGS_USE}"
export CXXFLAGS="${CXXFLAGS_USE}"
export FFLAGS="${FFLAGS_USE}"
export FCFLAGS="${FCFLAGS_USE}"
export LDFLAGS="${LDFLAGS_USE}"
%reconfigure --enable-shared --enable-static
make  %{?_smp_mflags}

pushd ../build32/
export CFLAGS="-O2 -ffat-lto-objects -fuse-linker-plugin -pipe -fPIC -m32 -mstackrealign -march=native -mtune=native"
export CXXFLAGS="-O2 -ffat-lto-objects -fuse-linker-plugin -fvisibility-inlines-hidden -pipe -fPIC -m32 -mstackrealign -march=native -mtune=native"
export LDFLAGS="-O2 -ffat-lto-objects -fuse-linker-plugin -pipe -fPIC -m32 -mstackrealign -march=native -mtune=native"
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
unset LD_LIBRARY_PATH
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
export ASFLAGS="${ASFLAGS}${ASFLAGS:+ }--32"
export CFLAGS="${CFLAGS}${CFLAGS:+ }-m32 -mstackrealign"
export CXXFLAGS="${CXXFLAGS}${CXXFLAGS:+ }-m32 -mstackrealign"
export LDFLAGS="${LDFLAGS}${LDFLAGS:+ }-m32 -mstackrealign"
%reconfigure --enable-shared --enable-static  --libdir=/usr/lib32 --build=i686-generic-linux-gnu --host=i686-generic-linux-gnu --target=i686-clr-linux-gnu
make  %{?_smp_mflags}
popd

%check
export LANG=C.UTF-8
unset http_proxy
unset https_proxy
unset no_proxy
export SSL_CERT_FILE=/var/cache/ca-certs/anchors/ca-certificates.crt
make %{?_smp_mflags} check
cd ../build32;
make %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1611836173
rm -rf %{buildroot}
pushd ../build32/
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/fax2ps
/usr/bin/fax2tiff
/usr/bin/pal2rgb
/usr/bin/ppm2tiff
/usr/bin/raw2tiff
/usr/bin/tiff2bw
/usr/bin/tiff2pdf
/usr/bin/tiff2ps
/usr/bin/tiff2rgba
/usr/bin/tiffcmp
/usr/bin/tiffcp
/usr/bin/tiffcrop
/usr/bin/tiffdither
/usr/bin/tiffdump
/usr/bin/tiffinfo
/usr/bin/tiffmedian
/usr/bin/tiffset
/usr/bin/tiffsplit

%files dev
%defattr(-,root,root,-)
/usr/include/tiff.h
/usr/include/tiffconf.h
/usr/include/tiffio.h
/usr/include/tiffio.hxx
/usr/include/tiffvers.h
/usr/lib64/libtiff.so
/usr/lib64/libtiffxx.so
/usr/lib64/pkgconfig/libtiff-4.pc
/usr/share/man/man3/TIFFClose.3tiff
/usr/share/man/man3/TIFFDataWidth.3tiff
/usr/share/man/man3/TIFFError.3tiff
/usr/share/man/man3/TIFFFieldDataType.3tiff
/usr/share/man/man3/TIFFFieldName.3tiff
/usr/share/man/man3/TIFFFieldPassCount.3tiff
/usr/share/man/man3/TIFFFieldReadCount.3tiff
/usr/share/man/man3/TIFFFieldTag.3tiff
/usr/share/man/man3/TIFFFieldWriteCount.3tiff
/usr/share/man/man3/TIFFFlush.3tiff
/usr/share/man/man3/TIFFGetField.3tiff
/usr/share/man/man3/TIFFOpen.3tiff
/usr/share/man/man3/TIFFPrintDirectory.3tiff
/usr/share/man/man3/TIFFRGBAImage.3tiff
/usr/share/man/man3/TIFFReadDirectory.3tiff
/usr/share/man/man3/TIFFReadEncodedStrip.3tiff
/usr/share/man/man3/TIFFReadEncodedTile.3tiff
/usr/share/man/man3/TIFFReadRGBAImage.3tiff
/usr/share/man/man3/TIFFReadRGBAStrip.3tiff
/usr/share/man/man3/TIFFReadRGBATile.3tiff
/usr/share/man/man3/TIFFReadRawStrip.3tiff
/usr/share/man/man3/TIFFReadRawTile.3tiff
/usr/share/man/man3/TIFFReadScanline.3tiff
/usr/share/man/man3/TIFFReadTile.3tiff
/usr/share/man/man3/TIFFSetDirectory.3tiff
/usr/share/man/man3/TIFFSetField.3tiff
/usr/share/man/man3/TIFFWarning.3tiff
/usr/share/man/man3/TIFFWriteDirectory.3tiff
/usr/share/man/man3/TIFFWriteEncodedStrip.3tiff
/usr/share/man/man3/TIFFWriteEncodedTile.3tiff
/usr/share/man/man3/TIFFWriteRawStrip.3tiff
/usr/share/man/man3/TIFFWriteRawTile.3tiff
/usr/share/man/man3/TIFFWriteScanline.3tiff
/usr/share/man/man3/TIFFWriteTile.3tiff
/usr/share/man/man3/TIFFbuffer.3tiff
/usr/share/man/man3/TIFFcodec.3tiff
/usr/share/man/man3/TIFFcolor.3tiff
/usr/share/man/man3/TIFFmemory.3tiff
/usr/share/man/man3/TIFFquery.3tiff
/usr/share/man/man3/TIFFsize.3tiff
/usr/share/man/man3/TIFFstrip.3tiff
/usr/share/man/man3/TIFFswab.3tiff
/usr/share/man/man3/TIFFtile.3tiff
/usr/share/man/man3/libtiff.3tiff

%files dev32
%defattr(-,root,root,-)
/usr/lib32/libtiff.so
/usr/lib32/libtiffxx.so
/usr/lib32/pkgconfig/32libtiff-4.pc
/usr/lib32/pkgconfig/libtiff-4.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/tiff-4.2.0/COPYRIGHT
/usr/share/doc/tiff-4.2.0/ChangeLog
/usr/share/doc/tiff-4.2.0/README.md
/usr/share/doc/tiff-4.2.0/RELEASE-DATE
/usr/share/doc/tiff-4.2.0/TODO
/usr/share/doc/tiff-4.2.0/VERSION
/usr/share/doc/tiff-4.2.0/html/TIFFTechNote2.html
/usr/share/doc/tiff-4.2.0/html/addingtags.html
/usr/share/doc/tiff-4.2.0/html/bugs.html
/usr/share/doc/tiff-4.2.0/html/build.html
/usr/share/doc/tiff-4.2.0/html/contrib.html
/usr/share/doc/tiff-4.2.0/html/document.html
/usr/share/doc/tiff-4.2.0/html/images.html
/usr/share/doc/tiff-4.2.0/html/images/back.gif
/usr/share/doc/tiff-4.2.0/html/images/bali.jpg
/usr/share/doc/tiff-4.2.0/html/images/cat.gif
/usr/share/doc/tiff-4.2.0/html/images/cover.jpg
/usr/share/doc/tiff-4.2.0/html/images/cramps.gif
/usr/share/doc/tiff-4.2.0/html/images/dave.gif
/usr/share/doc/tiff-4.2.0/html/images/info.gif
/usr/share/doc/tiff-4.2.0/html/images/jello.jpg
/usr/share/doc/tiff-4.2.0/html/images/jim.gif
/usr/share/doc/tiff-4.2.0/html/images/note.gif
/usr/share/doc/tiff-4.2.0/html/images/oxford.gif
/usr/share/doc/tiff-4.2.0/html/images/quad.jpg
/usr/share/doc/tiff-4.2.0/html/images/ring.gif
/usr/share/doc/tiff-4.2.0/html/images/smallliz.jpg
/usr/share/doc/tiff-4.2.0/html/images/strike.gif
/usr/share/doc/tiff-4.2.0/html/images/warning.gif
/usr/share/doc/tiff-4.2.0/html/index.html
/usr/share/doc/tiff-4.2.0/html/internals.html
/usr/share/doc/tiff-4.2.0/html/intro.html
/usr/share/doc/tiff-4.2.0/html/libtiff.html
/usr/share/doc/tiff-4.2.0/html/man/TIFFClose.3tiff.html
/usr/share/doc/tiff-4.2.0/html/man/TIFFDataWidth.3tiff.html
/usr/share/doc/tiff-4.2.0/html/man/TIFFError.3tiff.html
/usr/share/doc/tiff-4.2.0/html/man/TIFFFieldDataType.3tiff.html
/usr/share/doc/tiff-4.2.0/html/man/TIFFFieldName.3tiff.html
/usr/share/doc/tiff-4.2.0/html/man/TIFFFieldPassCount.3tiff.html
/usr/share/doc/tiff-4.2.0/html/man/TIFFFieldReadCount.3tiff.html
/usr/share/doc/tiff-4.2.0/html/man/TIFFFieldTag.3tiff.html
/usr/share/doc/tiff-4.2.0/html/man/TIFFFieldWriteCount.3tiff.html
/usr/share/doc/tiff-4.2.0/html/man/TIFFFlush.3tiff.html
/usr/share/doc/tiff-4.2.0/html/man/TIFFGetField.3tiff.html
/usr/share/doc/tiff-4.2.0/html/man/TIFFOpen.3tiff.html
/usr/share/doc/tiff-4.2.0/html/man/TIFFPrintDirectory.3tiff.html
/usr/share/doc/tiff-4.2.0/html/man/TIFFRGBAImage.3tiff.html
/usr/share/doc/tiff-4.2.0/html/man/TIFFReadDirectory.3tiff.html
/usr/share/doc/tiff-4.2.0/html/man/TIFFReadEncodedStrip.3tiff.html
/usr/share/doc/tiff-4.2.0/html/man/TIFFReadEncodedTile.3tiff.html
/usr/share/doc/tiff-4.2.0/html/man/TIFFReadRGBAImage.3tiff.html
/usr/share/doc/tiff-4.2.0/html/man/TIFFReadRGBAStrip.3tiff.html
/usr/share/doc/tiff-4.2.0/html/man/TIFFReadRGBATile.3tiff.html
/usr/share/doc/tiff-4.2.0/html/man/TIFFReadRawStrip.3tiff.html
/usr/share/doc/tiff-4.2.0/html/man/TIFFReadRawTile.3tiff.html
/usr/share/doc/tiff-4.2.0/html/man/TIFFReadScanline.3tiff.html
/usr/share/doc/tiff-4.2.0/html/man/TIFFReadTile.3tiff.html
/usr/share/doc/tiff-4.2.0/html/man/TIFFSetDirectory.3tiff.html
/usr/share/doc/tiff-4.2.0/html/man/TIFFSetField.3tiff.html
/usr/share/doc/tiff-4.2.0/html/man/TIFFWarning.3tiff.html
/usr/share/doc/tiff-4.2.0/html/man/TIFFWriteDirectory.3tiff.html
/usr/share/doc/tiff-4.2.0/html/man/TIFFWriteEncodedStrip.3tiff.html
/usr/share/doc/tiff-4.2.0/html/man/TIFFWriteEncodedTile.3tiff.html
/usr/share/doc/tiff-4.2.0/html/man/TIFFWriteRawStrip.3tiff.html
/usr/share/doc/tiff-4.2.0/html/man/TIFFWriteRawTile.3tiff.html
/usr/share/doc/tiff-4.2.0/html/man/TIFFWriteScanline.3tiff.html
/usr/share/doc/tiff-4.2.0/html/man/TIFFWriteTile.3tiff.html
/usr/share/doc/tiff-4.2.0/html/man/TIFFbuffer.3tiff.html
/usr/share/doc/tiff-4.2.0/html/man/TIFFcodec.3tiff.html
/usr/share/doc/tiff-4.2.0/html/man/TIFFcolor.3tiff.html
/usr/share/doc/tiff-4.2.0/html/man/TIFFmemory.3tiff.html
/usr/share/doc/tiff-4.2.0/html/man/TIFFquery.3tiff.html
/usr/share/doc/tiff-4.2.0/html/man/TIFFsize.3tiff.html
/usr/share/doc/tiff-4.2.0/html/man/TIFFstrip.3tiff.html
/usr/share/doc/tiff-4.2.0/html/man/TIFFswab.3tiff.html
/usr/share/doc/tiff-4.2.0/html/man/TIFFtile.3tiff.html
/usr/share/doc/tiff-4.2.0/html/man/fax2ps.1.html
/usr/share/doc/tiff-4.2.0/html/man/fax2tiff.1.html
/usr/share/doc/tiff-4.2.0/html/man/index.html
/usr/share/doc/tiff-4.2.0/html/man/libtiff.3tiff.html
/usr/share/doc/tiff-4.2.0/html/man/pal2rgb.1.html
/usr/share/doc/tiff-4.2.0/html/man/ppm2tiff.1.html
/usr/share/doc/tiff-4.2.0/html/man/raw2tiff.1.html
/usr/share/doc/tiff-4.2.0/html/man/tiff2bw.1.html
/usr/share/doc/tiff-4.2.0/html/man/tiff2pdf.1.html
/usr/share/doc/tiff-4.2.0/html/man/tiff2ps.1.html
/usr/share/doc/tiff-4.2.0/html/man/tiff2rgba.1.html
/usr/share/doc/tiff-4.2.0/html/man/tiffcmp.1.html
/usr/share/doc/tiff-4.2.0/html/man/tiffcp.1.html
/usr/share/doc/tiff-4.2.0/html/man/tiffcrop.1.html
/usr/share/doc/tiff-4.2.0/html/man/tiffdither.1.html
/usr/share/doc/tiff-4.2.0/html/man/tiffdump.1.html
/usr/share/doc/tiff-4.2.0/html/man/tiffgt.1.html
/usr/share/doc/tiff-4.2.0/html/man/tiffinfo.1.html
/usr/share/doc/tiff-4.2.0/html/man/tiffmedian.1.html
/usr/share/doc/tiff-4.2.0/html/man/tiffset.1.html
/usr/share/doc/tiff-4.2.0/html/man/tiffsplit.1.html
/usr/share/doc/tiff-4.2.0/html/misc.html
/usr/share/doc/tiff-4.2.0/html/support.html
/usr/share/doc/tiff-4.2.0/html/tools.html
/usr/share/doc/tiff-4.2.0/html/v3.4beta007.html
/usr/share/doc/tiff-4.2.0/html/v3.4beta016.html
/usr/share/doc/tiff-4.2.0/html/v3.4beta018.html
/usr/share/doc/tiff-4.2.0/html/v3.4beta024.html
/usr/share/doc/tiff-4.2.0/html/v3.4beta028.html
/usr/share/doc/tiff-4.2.0/html/v3.4beta029.html
/usr/share/doc/tiff-4.2.0/html/v3.4beta031.html
/usr/share/doc/tiff-4.2.0/html/v3.4beta032.html
/usr/share/doc/tiff-4.2.0/html/v3.4beta033.html
/usr/share/doc/tiff-4.2.0/html/v3.4beta034.html
/usr/share/doc/tiff-4.2.0/html/v3.4beta035.html
/usr/share/doc/tiff-4.2.0/html/v3.4beta036.html
/usr/share/doc/tiff-4.2.0/html/v3.5.1.html
/usr/share/doc/tiff-4.2.0/html/v3.5.2.html
/usr/share/doc/tiff-4.2.0/html/v3.5.3.html
/usr/share/doc/tiff-4.2.0/html/v3.5.4.html
/usr/share/doc/tiff-4.2.0/html/v3.5.5.html
/usr/share/doc/tiff-4.2.0/html/v3.5.6-beta.html
/usr/share/doc/tiff-4.2.0/html/v3.5.7.html
/usr/share/doc/tiff-4.2.0/html/v3.6.0.html
/usr/share/doc/tiff-4.2.0/html/v3.6.1.html
/usr/share/doc/tiff-4.2.0/html/v3.7.0.html
/usr/share/doc/tiff-4.2.0/html/v3.7.0alpha.html
/usr/share/doc/tiff-4.2.0/html/v3.7.0beta.html
/usr/share/doc/tiff-4.2.0/html/v3.7.0beta2.html
/usr/share/doc/tiff-4.2.0/html/v3.7.1.html
/usr/share/doc/tiff-4.2.0/html/v3.7.2.html
/usr/share/doc/tiff-4.2.0/html/v3.7.3.html
/usr/share/doc/tiff-4.2.0/html/v3.7.4.html
/usr/share/doc/tiff-4.2.0/html/v3.8.0.html
/usr/share/doc/tiff-4.2.0/html/v3.8.1.html
/usr/share/doc/tiff-4.2.0/html/v3.8.2.html
/usr/share/doc/tiff-4.2.0/html/v3.9.0beta.html
/usr/share/doc/tiff-4.2.0/html/v3.9.1.html
/usr/share/doc/tiff-4.2.0/html/v3.9.2.html
/usr/share/doc/tiff-4.2.0/html/v4.0.0.html
/usr/share/doc/tiff-4.2.0/html/v4.0.1.html
/usr/share/doc/tiff-4.2.0/html/v4.0.10.html
/usr/share/doc/tiff-4.2.0/html/v4.0.2.html
/usr/share/doc/tiff-4.2.0/html/v4.0.3.html
/usr/share/doc/tiff-4.2.0/html/v4.0.4.html
/usr/share/doc/tiff-4.2.0/html/v4.0.4beta.html
/usr/share/doc/tiff-4.2.0/html/v4.0.5.html
/usr/share/doc/tiff-4.2.0/html/v4.0.6.html
/usr/share/doc/tiff-4.2.0/html/v4.0.7.html
/usr/share/doc/tiff-4.2.0/html/v4.0.8.html
/usr/share/doc/tiff-4.2.0/html/v4.0.9.html
/usr/share/doc/tiff-4.2.0/html/v4.1.0.html
/usr/share/doc/tiff-4.2.0/html/v4.2.0.html

%files lib
%defattr(-,root,root,-)
/usr/lib64/libtiff.so.5
/usr/lib64/libtiff.so.5.6.0
/usr/lib64/libtiffxx.so.5
/usr/lib64/libtiffxx.so.5.6.0

%files lib32
%defattr(-,root,root,-)
/usr/lib32/libtiff.so.5
/usr/lib32/libtiff.so.5.6.0
/usr/lib32/libtiffxx.so.5
/usr/lib32/libtiffxx.so.5.6.0

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/fax2ps.1
/usr/share/man/man1/fax2tiff.1
/usr/share/man/man1/pal2rgb.1
/usr/share/man/man1/ppm2tiff.1
/usr/share/man/man1/raw2tiff.1
/usr/share/man/man1/tiff2bw.1
/usr/share/man/man1/tiff2pdf.1
/usr/share/man/man1/tiff2ps.1
/usr/share/man/man1/tiff2rgba.1
/usr/share/man/man1/tiffcmp.1
/usr/share/man/man1/tiffcp.1
/usr/share/man/man1/tiffcrop.1
/usr/share/man/man1/tiffdither.1
/usr/share/man/man1/tiffdump.1
/usr/share/man/man1/tiffgt.1
/usr/share/man/man1/tiffinfo.1
/usr/share/man/man1/tiffmedian.1
/usr/share/man/man1/tiffset.1
/usr/share/man/man1/tiffsplit.1

%files staticdev
%defattr(-,root,root,-)
/usr/lib64/libtiff.a
/usr/lib64/libtiffxx.a

%files staticdev32
%defattr(-,root,root,-)
/usr/lib32/libtiff.a
/usr/lib32/libtiffxx.a
